"""Add item and category

Revision ID: 83c8b1f8eb
Revises: 21c4aaf3766
Create Date: 2015-02-22 17:27:29.827586

"""

# revision identifiers, used by Alembic.
revision = '83c8b1f8eb'
down_revision = '21c4aaf3766'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import pyramidapp


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('original_image_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['item.uid'], name='fk_category_item', use_alter=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('tag',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name', 'parent_id', name='item_by_parent')
    )
    op.create_table('picture',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('original_image_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['item.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('item_tag',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.uid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uid'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tag')
    op.drop_table('picture')
    op.drop_table('item')
    op.drop_table('tag')
    op.drop_table('category')
    ### end Alembic commands ###
